[Apple] Support Mac Catalyst
microsoft/appcenter-sdk-react-native pull request #902
Opened 2021-03-04 05:46 UTC by DmitriyKirakosyan

Things to consider before you submit the PR:

* [ ] Has `CHANGELOG.md` been updated?
* [ ] Are tests passing locally?
* [ ] Are the files formatted correctly?
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?

## Description

This PR adds support for Mac Catalyst by adding the requiring binaries to the `AppCenterReactNativeShared` 
 xcfromework.

## Related PRs or issues

This addresses the issue https://github.com/microsoft/appcenter-sdk-react-native/issues/901

## Misc

Fat framework was converted to xcframework here https://github.com/microsoft/appcenter-sdk-react-native/pull/896 for the `AppCenterReactNativeShared` project, however the mac catalyst binary was missing in the final xcframework.

2021-03-04 06:32 UTC, MatkovIvan requested changes
```
AppCenterReactNativeShared.xcframework/ios-x86_64-maccatalyst/AppCenterReactNativeShared.framework/Headers/Headers: No such file or directory
```

2021-03-04 11:28 UTC, MatkovIvan approved these changes

2021-03-16 12:56 UTC, russelarms requested changes
TestApp build failed on Catalyst (Big Sur) with:
 ```
AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.m:28:9: 'AppCenterReactNativeShared/AppCenterReactNativeShared.h' file not found
```
on Catalina:
```
Undefined symbols for architecture x86_64
```

2021-03-17 13:49 UTC, russelarms reviewed
Errors were due to Cocoapods version 1.10.0. An update to 1.10.1 resolved them.

2021-03-17 14:33 UTC, DmitriyKirakosyan commented on CHANGELOG.md
> +* **[Feature]** Support Mac Catalyst.
```suggestion
* **[Feature]** Support Mac Catalyst. Cocoapods 1.10.1+ is required.
```

2021-03-18 04:32 UTC, MatkovIvan submitted a review, later dismissed

2021-03-18 14:13 UTC, russelarms approved these changes

2021-03-18 16:28 UTC, merged